# Server Port
server.port=8080

# Database — change YOUR_PASSWORD to your actual MySQL password
spring.datasource.url=jdbc:mysql://localhost:3306/codestreak_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Lakshana141105

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=codestreak_super_secret_key_minimum_256_bits_long_2024
app.jwt.expiration=86400000